version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      google-cloud:
        patterns:
          - "googleapis"
          - "google-auth-library"
      swc:
        patterns:
          - "@swc/*"
      eslint:
        patterns:
          - "@eslint/*"
          - "@stylistic/*"
          - "eslint"
          - "eslint-*"
          - "typescript-eslint"
          - "@typescript-eslint/*"
