name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    concurrency: release-please
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
  
  publish:
    runs-on: ubuntu-latest
    concurrency: publish
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
  
    steps:
    - uses: actions/checkout@v4
    - name: Setup node with cached node_modules
      uses: ./.github/actions/setup-node-cached
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - name: Prepare
      run: npm run prepare
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      run: npm publish
